title: 鳥取大砂丘Rails勉強会

lang: ja

timezone: Asia/Tokyo

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

url: https://tottori-rails.github.io

github_username: tottori-rails

repository: tottori-rails/tottori-rails.github.io
